<a href="https://colab.research.google.com/github/OVP2023/dataPY/blob/main/%D0%BC%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%8B1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


Задание 1

    Создайте матрицу 3 на 3, заполненную числами от 1 до 9
    Прибавьте к ней матрицу с единицами на диагонале
    Умножьте полученную матрицу на вектор (1, 2, 3)
    Вычислить транспонированную матрицу

от полученной в результате прибавления матрицы
Посчитайте обратную матрицу к полученной в результате прибавления матрице

In [ ]:
import numpy as np
A1=np.array([[1,2,3],[4,5,6],[7,8,9]])
A1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
A2=np.eye(3)
A2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
A3=A1+A2
A3

array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

In [ ]:
A4=A3@np.array([1,2,3])
A4

array([15., 34., 53.])

In [ ]:
A5=np.transpose(A3)
A5

array([[ 2.,  4.,  7.],
       [ 2.,  6.,  8.],
       [ 3.,  6., 10.]])


Задание 2

Найдите собственные значения и собственные вектора матрицы:

m = np.array([[2, 2],
              [1, 3]])
print(m)


In [ ]:
m = np.array([[2, 2], [1, 3]])
print(m)

[[2 2]
 [1 3]]


In [ ]:
sn=np.linalg.eig(m)
sn


EigResult(eigenvalues=array([1., 4.]), eigenvectors=array([[-0.89442719, -0.70710678],
       [ 0.4472136 , -0.70710678]]))


Задание 3

Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

P.S. Матрица должна быть ненулевой и размерностью не менее 2!


In [ ]:
A7=np.array([[3,5],[1,2]])
A7

array([[3, 5],
       [1, 2]])

In [ ]:
np.linalg.det(A7)

1.0000000000000004